//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionsLeague.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChampionsLeague.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Clubs.
        /// </summary>
        internal static string BestClubsFormTitle {
            get {
                return ResourceManager.GetString("BestClubsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champions League.
        /// </summary>
        internal static string ChampionsLeagueFormTitle {
            get {
                return ResourceManager.GetString("ChampionsLeagueFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Footballer.
        /// </summary>
        internal static string CreateFootballerFormTitle {
            get {
                return ResourceManager.GetString("CreateFootballerFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Footballer.
        /// </summary>
        internal static string EditFootballerFormTitle {
            get {
                return ResourceManager.GetString("EditFootballerFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit multiple footballers!.
        /// </summary>
        internal static string EditMultipleFootballerWarningText {
            get {
                return ResourceManager.GetString("EditMultipleFootballerWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change in footballers count. Previous count: {0}. New count: {1}..
        /// </summary>
        internal static string LogChangeFootballersCountText {
            get {
                return ResourceManager.GetString("LogChangeFootballersCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register change count handler..
        /// </summary>
        internal static string RegisterLogChangeCountHandlerText {
            get {
                return ResourceManager.GetString("RegisterLogChangeCountHandlerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister change count handler..
        /// </summary>
        internal static string UnregisterLogChangeCountHandlerText {
            get {
                return ResourceManager.GetString("UnregisterLogChangeCountHandlerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want footballer without name?.
        /// </summary>
        internal static string WithoutNameFootballerFormWarningText {
            get {
                return ResourceManager.GetString("WithoutNameFootballerFormWarningText", resourceCulture);
            }
        }
    }
}
